version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm build
  test:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: cd FrontEnd/Hopsy
      - run: npm test 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
