version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm build
  test:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: cd FrontEnd
      - run: npm install
      - run: npm install jest-junit jest-cli jest
      - run: npm install @babel/plugin-proposal-class-properties --save-dev
      - run: npm test 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
