jobs:
  build:
    working_directory: ~/CSC308/FrontEnd/Hopsy
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test
